"use client"

import type React from "react"
import { useRef, useEffect } from "react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Brain, Play, Pause } from "lucide-react"
import ReactMarkdown from "react-markdown"

interface CosmicWorkflowExecutionProps {
  state: any
  dispatch: React.Dispatch<any>
}

export const CosmicWorkflowExecution: React.FC<CosmicWorkflowExecutionProps> = ({ state, dispatch }) => {
  const outputEndRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (outputEndRef.current) {
      outputEndRef.current.scrollIntoView({ behavior: "smooth" })
    }
  }, [state.workflowOutput])

  const runCosmicWorkflow = async () => {
    if (!state.apiKey) {
      dispatch({
        type: "SET_ERROR",
        payload: "API key is required to execute the cosmic workflow",
      })
      return
    }

    dispatch({ type: "SET_IS_RUNNING", payload: true })
    dispatch({ type: "SET_WORKFLOW_OUTPUT", payload: "" })
    dispatch({ type: "SET_THINKING_LOG", payload: [] })
    dispatch({ type: "SET_ERROR", payload: null })

    try {
      // Simulate workflow execution
      dispatch({ type: "APPEND_THINKING_LOG", payload: "Initializing cosmic workflow..." })
      await new Promise((resolve) => setTimeout(resolve, 1000))

      dispatch({ type: "APPEND_THINKING_LOG", payload: "Connecting to cosmic agents..." })
      await new Promise((resolve) => setTimeout(resolve, 1000))

      for (let i = 0; i < state.agents.length; i++) {
        const agent = state.agents[i]
        dispatch({ type: "APPEND_THINKING_LOG", payload: `Activating agent: ${agent.name}...` })
        await new Promise((resolve) => setTimeout(resolve, 800))

        dispatch({
          type: "APPEND_WORKFLOW_OUTPUT",
          payload: `## Agent: ${agent.name}\n\n${state.workflowInput ? `Processing input: "${state.workflowInput}"\n\n` : ""}`,
        })

        await new Promise((resolve) => setTimeout(resolve, 1200))

        dispatch({
          type: "APPEND_WORKFLOW_OUTPUT",
          payload: `Output: This is a simulated response from ${agent.name}. In a real implementation, this would be generated by the Groq API based on the agent's prompts.\n\n`,
        })
      }

      dispatch({ type: "APPEND_THINKING_LOG", payload: "Cosmic workflow completed successfully." })
    } catch (error) {
      console.error("Error running cosmic workflow:", error)
      dispatch({
        type: "SET_ERROR",
        payload: error.message || "An unexpected cosmic disturbance occurred.",
      })
    } finally {
      dispatch({ type: "SET_IS_RUNNING", payload: false })
    }
  }

  return (
    <Card
      className="border border-[#333] bg-black/60 shadow-md"
      style={{ boxShadow: "0 0 30px rgba(233, 30, 99, 0.1)" }}
    >
      <CardHeader>
        <CardTitle className="flex items-center text-[#e91e63]">
          <Brain className="mr-2 text-[#e91e63]" />
          Cosmic Workflow Execution
        </CardTitle>
      </CardHeader>
      <CardContent>
        <textarea
          value={state.workflowInput}
          onChange={(e) => dispatch({ type: "SET_WORKFLOW_INPUT", payload: e.target.value })}
          placeholder="Enter the cosmic prompt to initiate the workflow..."
          className="w-full h-32 p-2 mb-4 bg-black text-white border border-[#333] rounded-md placeholder-gray-500 focus:border-[#e91e63] focus:ring-[#e91e63]"
        />
        <div className="flex space-x-2 mb-4">
          <Button
            onClick={runCosmicWorkflow}
            disabled={state.isRunning}
            className="bg-[#e91e63] hover:bg-[#d81b60] text-white"
          >
            {state.isRunning ? (
              <span className="animate-pulse">Cosmic Processing...</span>
            ) : (
              <>
                <Play size={16} className="mr-2" />
                Execute Cosmic Workflow
              </>
            )}
          </Button>
          <Button
            onClick={() => dispatch({ type: "SET_PAUSED", payload: !state.paused })}
            disabled={!state.isRunning}
            className="bg-[#333] hover:bg-[#444] text-white"
          >
            {state.paused ? (
              <>
                <Play size={16} className="mr-2" />
                Resume Cosmic Flow
              </>
            ) : (
              <>
                <Pause size={16} className="mr-2" />
                Pause Cosmic Flow
              </>
            )}
          </Button>
        </div>
        <div className="mb-4">
          <h3 className="text-lg font-semibold mb-2 text-[#e91e63]">Cosmic Thinking Log:</h3>
          <ScrollArea className="h-40 bg-black/40 p-2 rounded-md overflow-auto border border-[#333]">
            {state.thinkingLog.map((log: string, index: number) => (
              <div key={index} className="text-gray-300">
                {log}
              </div>
            ))}
          </ScrollArea>
        </div>
        <div className="mb-4">
          <h3 className="text-lg font-semibold mb-2 text-[#e91e63]">Cosmic Workflow Output:</h3>
          <ScrollArea className="h-96 bg-black/40 p-4 rounded-md overflow-auto border border-[#333]">
            <ReactMarkdown
              className="text-gray-300"
              components={{
                code({ node, inline, className, children, ...props }) {
                  return !inline ? (
                    <pre className="bg-black/60 p-2 rounded-md overflow-x-auto">
                      <code className={className} {...props}>
                        {children}
                      </code>
                    </pre>
                  ) : (
                    <code className="bg-black/60 px-1 rounded" {...props}>
                      {children}
                    </code>
                  )
                },
              }}
            >
              {state.workflowOutput}
            </ReactMarkdown>
            <div ref={outputEndRef} />
          </ScrollArea>
        </div>
      </CardContent>
    </Card>
  )
}
